[package]
name = "swiper"
version = "0.0.0"
edition = "2024"
description = "placeholder for async task managemenet library"
license = "MIT OR Apache-2.0"

[dependencies]

[features]
default = ["std"]
std = []
